export const weather = {
    GETWEATHER: 'GETWEATHER',
    POSTWEATHER: 'POSTWEATHER',
    DELETEONEWEATHER: 'DELETEONEWEATHER',
    TEMPERATURE: 'TEMPERATURE'
}

export const GET_ERRORS = "GET_ERRORS";

export const USER_LOADING = "USER_LOADING";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const DELETE_ERROR_MSGS = 'DELETE_ERROR_MSGS';